name: miapp
services:
  db:
    image: mysql:9.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: "512M"
        reservations:
          cpus: "2"
          memory: "256M"
  app:
    image: ghcr.io/sergio123456789/backend-node-docker-lab1:lab-1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST:  ${MYSQL_HOST}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      APP_VERSION: ${APP_VERSION:-1.0.0}
    ports:
      - "3000:4000"
volumes:
  db_data:
